name: Compatibility Request
description: Request support for a device that is not supported
title: "[机型适配]: "
labels: ["compatibility"]
body:
  - type: markdown
    attributes:
      value: |
        麻烦花时间填写一下内容，请提供尽可能多的信息。
        
        
        **重要提醒：**
        **作者仅打算适配拯救者系列机型，其他机型随缘。**
        
        
  - type: input
    id: version
    attributes:
      label: Version
      description: 你所使用的Lenovo Legion Toolkit版本？
      placeholder: e.g. 2.5.1
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: 你在使用的操作系统？
      placeholder: e.g. Windows 11 21H2 build 22000
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: 你在使用的笔记本型号？
      placeholder: e.g. Legion 5 Pro 16ACH6
    validations:
      required: true
  - type: textarea
    id: what-was-test
    attributes:
      label: 你测试了LLT的哪些功能？
      description: 简明地描述一下你所测试的功能。
      placeholder: 在这里输入...
    validations:
      required: true
  - type: textarea
    id: what-is-broken
    attributes:
      label: LLT的哪些功能运行不正常？
      description: 简明地描述一下运行不正常的功能。
      placeholder: 在这里输入...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: 在这里提交logs。你可以阅读README查找如何收集logs。
  - type: textarea
    id: additional
    attributes:
      label: 补充
      description: 可以使用截图或者详细的语言描述你的问题。
